import type { StructureBuilder } from 'sanity/structure'

// Define the hierarchy of the dashboard
export const structure = (S: StructureBuilder) =>
    S.list()
        .title('Konten Website')
        .items([
            // 1. News Management (Centralized)
            S.listItem()
                .title('Pusat Berita & Artikel')
                .child(
                    S.list()
                        .title('Manajemen Konten Berita')
                        .items([
                            S.documentTypeListItem('news').title('Semua Artikel'),
                            S.divider(),
                            S.documentTypeListItem('category').title('Kategori Berita'),
                            S.documentTypeListItem('teamMember').title('Daftar Penulis'),
                        ])
                ),

            S.divider(),

            // 2. Site Settings (Singleton)
            S.listItem()
                .title('Pengaturan Situs')
                .child(
                    S.document()
                        .schemaType('siteSettings')
                        .documentId('siteSettings')
                        .title('Pengaturan Situs')
                ),

            S.divider(),

            // 3. Group by Pages
            S.listItem()
                .title('Halaman Beranda')
                .child(
                    S.list()
                        .title('Komponen Beranda')
                        .items([
                            S.documentTypeListItem('landingHero').title('Hero Section'),
                            S.documentTypeListItem('service').title('Layanan (4 Utama)'),
                            S.documentTypeListItem('impactPillar').title('Pilar Impact'),

                            S.documentTypeListItem('partner').title('Partners'),
                            S.documentTypeListItem('testimonial').title('Testimonials'),
                        ])
                ),

            S.listItem()
                .title('Halaman PSB')
                .child(
                    S.document()
                        .schemaType('psbPage')
                        .documentId('psbPage')
                        .title('Konten PSB')
                ),

            S.listItem()
                .title('Halaman Tentang Kami')
                .child(
                    S.list()
                        .title('Komponen Tentang Kami')
                        .items([
                            S.listItem()
                                .title('Konten Halaman (Profil)')
                                .child(
                                    S.document()
                                        .schemaType('aboutPage')
                                        .documentId('aboutPage')
                                        .title('Konten Halaman Profil')
                                ),
                            S.divider(),
                            S.documentTypeListItem('teamMember').title('Tim & Pengurus'),
                            S.documentTypeListItem('facility').title('Fasilitas'),
                        ])
                ),

            S.divider(),

            // 3. Fallback for other items, EXCLUDING the ones we already handled AND the ones we want to hide (Donation)
            ...S.documentTypeListItems().filter(
                (listItem) =>
                    ![
                        'siteSettings',
                        'psbPage',
                        'landingHero',

                        'partner',
                        'testimonial',
                        'news',
                        'teamMember',
                        'facility',
                        'donationProgram', // Explicitly excluded as per user request
                        'media.tag', // Often auto-generated by plugins, can keep or hide. keeping for now if it exists.
                    ].includes(listItem.getId() || '')
            ),
        ])
