/**
 * Constants untuk modul akademik
 * Daftar surat Al-Quran dan opsi Iqra'
 */

// Daftar 114 Surat Al-Quran
export const DAFTAR_SURAT_AL_QURAN = [
  'Al-Fatihah',
  'Al-Baqarah',
  'Ali Imran',
  'An-Nisa',
  'Al-Maidah',
  'Al-An\'am',
  'Al-A\'raf',
  'Al-Anfal',
  'At-Taubah',
  'Yunus',
  'Hud',
  'Yusuf',
  'Ar-Ra\'d',
  'Ibrahim',
  'Al-Hijr',
  'An-Nahl',
  'Al-Isra',
  'Al-Kahf',
  'Maryam',
  'Ta Ha',
  'Al-Anbiya',
  'Al-Hajj',
  'Al-Mu\'minun',
  'An-Nur',
  'Al-Furqan',
  'Asy-Syu\'ara',
  'An-Naml',
  'Al-Qasas',
  'Al-Ankabut',
  'Ar-Rum',
  'Luqman',
  'As-Sajdah',
  'Al-Ahzab',
  'Saba',
  'Fathir',
  'Ya Sin',
  'As-Saffat',
  'Sad',
  'Az-Zumar',
  'Ghafir',
  'Fussilat',
  'Asy-Syura',
  'Az-Zukhruf',
  'Ad-Dukhan',
  'Al-Jasiyah',
  'Al-Ahqaf',
  'Muhammad',
  'Al-Fath',
  'Al-Hujurat',
  'Qaf',
  'Adz-Dzariyat',
  'At-Tur',
  'An-Najm',
  'Al-Qamar',
  'Ar-Rahman',
  'Al-Waqi\'ah',
  'Al-Hadid',
  'Al-Mujadilah',
  'Al-Hasyr',
  'Al-Mumtahanah',
  'As-Saff',
  'Al-Jumu\'ah',
  'Al-Munafiqun',
  'At-Taghabun',
  'At-Talaq',
  'At-Tahrim',
  'Al-Mulk',
  'Al-Qalam',
  'Al-Haqqah',
  'Al-Ma\'arij',
  'Nuh',
  'Al-Jinn',
  'Al-Muzzammil',
  'Al-Muddaththir',
  'Al-Qiyamah',
  'Al-Insan',
  'Al-Mursalat',
  'An-Naba',
  'An-Nazi\'at',
  'Abasa',
  'At-Takwir',
  'Al-Infitar',
  'Al-Mutaffifin',
  'Al-Insyiqaq',
  'Al-Buruj',
  'At-Tariq',
  'Al-A\'la',
  'Al-Ghasyiyah',
  'Al-Fajr',
  'Al-Balad',
  'Asy-Syams',
  'Al-Lail',
  'Ad-Duha',
  'Asy-Syarh',
  'At-Tin',
  'Al-\'Alaq',
  'Al-Qadr',
  'Al-Bayyinah',
  'Az-Zalzalah',
  'Al-\'Adiyat',
  'Al-Qari\'ah',
  'At-Takatsur',
  'Al-\'Asr',
  'Al-Humazah',
  'Al-Fil',
  'Quraisy',
  'Al-Ma\'un',
  'Al-Kausar',
  'Al-Kafirun',
  'An-Nasr',
  'Al-Lahab',
  'Al-Ikhlas',
  'Al-Falaq',
  'An-Nas',
] as const;

// Surat-surat pendek yang biasa dihafal untuk TPQ (Juz 30 dan sebagian Juz 29)
export const SURAT_PENDEK_TPQ = [
  'Al-Fatihah',
  'An-Nas',
  'Al-Falaq',
  'Al-Ikhlas',
  'Al-Lahab',
  'An-Nasr',
  'Al-Kafirun',
  'Al-Kausar',
  'Al-Ma\'un',
  'Quraisy',
  'Al-Fil',
  'Al-Humazah',
  'Al-\'Asr',
  'At-Takatsur',
  'Al-Qari\'ah',
  'Al-\'Adiyat',
  'Az-Zalzalah',
  'Al-Bayyinah',
  'Al-Qadr',
  'Al-\'Alaq',
  'At-Tin',
  'Asy-Syarh',
  'Ad-Duha',
  'Al-Lail',
  'Asy-Syams',
  'Al-Balad',
  'Al-Fajr',
  'Al-Ghasyiyah',
  'Al-A\'la',
  'At-Tariq',
  'Al-Buruj',
  'Al-Insyiqaq',
  'Al-Mutaffifin',
  'Al-Infitar',
  'At-Takwir',
  'Abasa',
  'An-Nazi\'at',
  'An-Naba',
] as const;

// Opsi Iqra' (Jilid 1-6)
export const IQRA_OPTIONS = [
  { value: '1', label: 'Iqra\' 1' },
  { value: '2', label: 'Iqra\' 2' },
  { value: '3', label: 'Iqra\' 3' },
  { value: '4', label: 'Iqra\' 4' },
  { value: '5', label: 'Iqra\' 5' },
  { value: '6', label: 'Iqra\' 6' },
] as const;

export const AGENDA_JENIS_OPTIONS = [
  { value: 'Absensi', label: 'Absensi' },
  { value: 'Setoran', label: 'Setoran' },
  { value: 'Gabungan', label: 'Gabungan (Absensi + Setoran)' },
] as const;

export const AGENDA_FREKUENSI_OPTIONS = [
  { value: 'Harian', label: 'Harian' },
  { value: 'Mingguan', label: 'Mingguan' },
  { value: 'Khusus', label: 'Kegiatan Khusus' },
] as const;

export const AGENDA_HARI_OPTIONS = [
  'Senin',
  'Selasa',
  'Rabu',
  'Kamis',
  'Jumat',
  'Sabtu',
  'Ahad',
] as const;

